name: Create release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
        run: |
          cd ${{github.workspace}}
          echo $tag
          echo $tag > data.txt
          gh release upload ${{github.event.release.tag_name}} data.txt
